POST http://192.168.0.179:8080/api/v1/user/register HTTP/1.1
content-type: application/json

{
    "username": "dummy",
    "first_name": "Konstantin",
    "last_name":  "Gasser",
    "password": "hello",
    "orgn_domain": "datalab.dev",
    "orgn_position": "Software Engineer"
}

###
POST http://192.168.0.179:8080/api/v1/user/login HTTP/1.1
content-type: application/json

{
    "username": "dummy",
    "password": "hello"
}

###
GET http://192.168.0.179:8080/api/v1/user/profile HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxMjU0MDk5LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI1YmM1NGE4Ni03ZDllLTQwOWUtYjg3Ny03YzE3ZWY0ODQ0MTQifQ.oxQK9xlFBKE8fFBpv8PKupXcGts10y2TYSeGkor9DeI

###
GET http://192.168.0.179:8080/api/v1/user/profile/colleagues HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxMjU0MDk5LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI1YmM1NGE4Ni03ZDllLTQwOWUtYjg3Ny03YzE3ZWY0ODQ0MTQifQ.oxQK9xlFBKE8fFBpv8PKupXcGts10y2TYSeGkor9DeI

###
POST http://192.168.0.179:8080/api/v1/user/profile/update HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxMjU0MDk5LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI1YmM1NGE4Ni03ZDllLTQwOWUtYjg3Ny03YzE3ZWY0ODQ0MTQifQ.oxQK9xlFBKE8fFBpv8PKupXcGts10y2TYSeGkor9DeI

{
    "first_name": "Konstantin",
    "last_name":  "Gasser",
    "orgn_position": "Software Engineer",
    "profile_img_url": "some/path/to/image"
}

###
POST http://192.168.0.179:8080/api/v1/app/create HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxMjU0MDk5LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI1YmM1NGE4Ni03ZDllLTQwOWUtYjg3Ny03YzE3ZWY0ODQ0MTQifQ.oxQK9xlFBKE8fFBpv8PKupXcGts10y2TYSeGkor9DeI

{
    "app_name": "dummy#2",
    "app_URL":  "http://dummy.io",
    "app_description": "Data Backend session init test"
}

###
GET http://192.168.0.179:8080/api/v1/app/get?app=2692042e-df8f-45a4-a50d-fdc0828782d6 HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxMjU0MDk5LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI1YmM1NGE4Ni03ZDllLTQwOWUtYjg3Ny03YzE3ZWY0ODQ0MTQifQ.oxQK9xlFBKE8fFBpv8PKupXcGts10y2TYSeGkor9DeI

###
GET http://192.168.0.179:8080/api/v1/app/getall HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxMjU0MDk5LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI1YmM1NGE4Ni03ZDllLTQwOWUtYjg3Ny03YzE3ZWY0ODQ0MTQifQ.oxQK9xlFBKE8fFBpv8PKupXcGts10y2TYSeGkor9DeI

###
POST http://192.168.0.179:8080/api/v1/app/token/create HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxMjU0MDk5LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI1YmM1NGE4Ni03ZDllLTQwOWUtYjg3Ny03YzE3ZWY0ODQ0MTQifQ.oxQK9xlFBKE8fFBpv8PKupXcGts10y2TYSeGkor9DeI

{
    "app_name": "dummy#2",
    "app_uuid": "2692042e-df8f-45a4-a50d-fdc0828782d6",
    "owner_domain": "datalab.dev",
    "app_origin": "http://test.io"
}

###
POST http://192.168.0.179:8080/api/v1/app/config/upsert?flag=funnel HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxMjU0MDk5LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI1YmM1NGE4Ni03ZDllLTQwOWUtYjg3Ny03YzE3ZWY0ODQ0MTQifQ.oxQK9xlFBKE8fFBpv8PKupXcGts10y2TYSeGkor9DeI

{
    "app_uuid": "cbd84e62-cb3d-4217-a367-0e343cbb5bc0",
    "stages": [
        {
            "id": 1,
            "name": "Stage Zero",
            "transition": "btn_add_to"
        },
        {
            "id": 2,
            "name": "Stage One",
            "transition": "btn_process"
        },
        {
            "id": 3,
            "name": "Stage Two",
            "transition": "btn_buy"
        }
    ]
}

###
POST http://192.168.0.179:8080/api/v1/app/config/upsert?flag=campaign HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxMjU0MDk5LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI1YmM1NGE4Ni03ZDllLTQwOWUtYjg3Ny03YzE3ZWY0ODQ0MTQifQ.oxQK9xlFBKE8fFBpv8PKupXcGts10y2TYSeGkor9DeI

{
    "app_uuid": "cbd84e62-cb3d-4217-a367-0e343cbb5bc0",
    "records": [
        {
            "id": 1,
            "name": "Summer Sales",
            "prefix": "summer"
        }
    ]
}

###
POST http://192.168.0.179:8080/api/v1/app/config/upsert?flag=btn_time HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxMjU0MDk5LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI1YmM1NGE4Ni03ZDllLTQwOWUtYjg3Ny03YzE3ZWY0ODQ0MTQifQ.oxQK9xlFBKE8fFBpv8PKupXcGts10y2TYSeGkor9DeI

{
    "app_uuid": "cbd84e62-cb3d-4217-a367-0e343cbb5bc0",
    "btn_defs": [
        {
            "id": 1,
            "name": "Order Button",
            "btn_name": "btn_order"
        }
    ]
}