POST http://localhost:8080/api/v1/user/register HTTP/1.1
content-type: application/json

{
    "username": "dummy1",
    "first_name": "Konstantin",
    "last_name":  "Gasser",
    "password": "hello",
    "orgn_domain": "datalab.dev",
    "orgn_position": "Software Engineer"
}

###
POST http://localhost:8080/api/v1/user/login HTTP/1.1
content-type: application/json

{
    "username": "dummy",
    "password": "hello"
}

###
GET http://localhost:8080/api/v1/user/profile HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbeyJhcHBfdXVpZCI6ImQ2NGZmYjdlLWQzODQtNDEyOC04Yjc4LWNlMWQwYTk2OTM1YSIsInJvbGUiOjB9XSwiZXhwIjoxNjIxNDYzNTU1LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI3MGVkMTZmMi04YmYwLTQ3ZjctYmU0Mi02Y2YwMTIwMjE5MmUifQ.Cia4cN92Eo5iIbOkxjCLwaKeh2FnoNcF6B-qtFLAfjw

###
GET http://localhost:8080/api/v1/user/profile/colleagues HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbeyJhcHBfdXVpZCI6ImQ2NGZmYjdlLWQzODQtNDEyOC04Yjc4LWNlMWQwYTk2OTM1YSIsInJvbGUiOjB9XSwiZXhwIjoxNjIxNDYzNTU1LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI3MGVkMTZmMi04YmYwLTQ3ZjctYmU0Mi02Y2YwMTIwMjE5MmUifQ.Cia4cN92Eo5iIbOkxjCLwaKeh2FnoNcF6B-qtFLAfjw

###
POST http://localhost:8080/api/v1/user/profile/update HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbeyJhcHBfdXVpZCI6ImQ2NGZmYjdlLWQzODQtNDEyOC04Yjc4LWNlMWQwYTk2OTM1YSIsInJvbGUiOjB9XSwiZXhwIjoxNjIxNDYzNTU1LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI3MGVkMTZmMi04YmYwLTQ3ZjctYmU0Mi02Y2YwMTIwMjE5MmUifQ.Cia4cN92Eo5iIbOkxjCLwaKeh2FnoNcF6B-qtFLAfjw

{
    "first_name": "Konstantin",
    "last_name":  "Gasser",
    "orgn_position": "Software Engineer",
    "profile_img_url": "some/path/to/image"
}

###
POST http://localhost:8080/api/v1/app/create HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbeyJhcHBfdXVpZCI6ImQ2NGZmYjdlLWQzODQtNDEyOC04Yjc4LWNlMWQwYTk2OTM1YSIsInJvbGUiOjB9XSwiZXhwIjoxNjIxNDYzNTU1LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI3MGVkMTZmMi04YmYwLTQ3ZjctYmU0Mi02Y2YwMTIwMjE5MmUifQ.Cia4cN92Eo5iIbOkxjCLwaKeh2FnoNcF6B-qtFLAfjw

{
    "app_name": "dummy#1",
    "app_URL":  "http://dummy#1.io",
    "app_description": "App Test #1"
}

###
GET http://localhost:8080/api/v1/app/get?app=923d323d-5f86-402e-921c-9c59a635bb2d HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbeyJhcHBfdXVpZCI6ImQ2NGZmYjdlLWQzODQtNDEyOC04Yjc4LWNlMWQwYTk2OTM1YSIsInJvbGUiOjB9LHsiYXBwX3V1aWQiOiJjYTIzYzg0Yy1jOTI4LTQ4ZjMtOTU3NS0wOGY1MzBlNWJiOTEiLCJyb2xlIjowfSx7ImFwcF91dWlkIjoiNTU1MjUyMDItMDBmMS00MGI1LWJhMzQtMDNlMWI5MTI3NWM2Iiwicm9sZSI6MH0seyJhcHBfdXVpZCI6IjkyM2QzMjNkLTVmODYtNDAyZS05MjFjLTljNTlhNjM1YmIyZCIsInJvbGUiOjB9XSwiZXhwIjoxNjIxNTMxMzIzLCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI3MGVkMTZmMi04YmYwLTQ3ZjctYmU0Mi02Y2YwMTIwMjE5MmUifQ.81k5-6Vqhxv5h4fleX9DbEXHlu721a2s4aL96Vz40Cg

###
GET http://localhost:8080/api/v1/app/getall HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbeyJhcHBfdXVpZCI6ImQ2NGZmYjdlLWQzODQtNDEyOC04Yjc4LWNlMWQwYTk2OTM1YSIsInJvbGUiOjB9LHsiYXBwX3V1aWQiOiJjYTIzYzg0Yy1jOTI4LTQ4ZjMtOTU3NS0wOGY1MzBlNWJiOTEiLCJyb2xlIjowfSx7ImFwcF91dWlkIjoiNTU1MjUyMDItMDBmMS00MGI1LWJhMzQtMDNlMWI5MTI3NWM2Iiwicm9sZSI6MH0seyJhcHBfdXVpZCI6IjkyM2QzMjNkLTVmODYtNDAyZS05MjFjLTljNTlhNjM1YmIyZCIsInJvbGUiOjB9XSwiZXhwIjoxNjIxNTMxMzIzLCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI3MGVkMTZmMi04YmYwLTQ3ZjctYmU0Mi02Y2YwMTIwMjE5MmUifQ.81k5-6Vqhxv5h4fleX9DbEXHlu721a2s4aL96Vz40Cg

###
POST http://localhost:8080/api/v1/app/token/create HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbeyJhcHBfdXVpZCI6ImQ2NGZmYjdlLWQzODQtNDEyOC04Yjc4LWNlMWQwYTk2OTM1YSIsInJvbGUiOjB9XSwiZXhwIjoxNjIxNDYzNTU1LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI3MGVkMTZmMi04YmYwLTQ3ZjctYmU0Mi02Y2YwMTIwMjE5MmUifQ.Cia4cN92Eo5iIbOkxjCLwaKeh2FnoNcF6B-qtFLAfjw

{
    "app_name": "dummy#2",
    "app_uuid": "2692042e-df8f-45a4-a50d-fdc0828782d6",
    "owner_domain": "datalab.dev",
    "app_origin": "http://test.io"
}

###
POST http://localhost:8080/api/v1/app/config/upsert?flag=funnel HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbeyJhcHBfdXVpZCI6ImQ2NGZmYjdlLWQzODQtNDEyOC04Yjc4LWNlMWQwYTk2OTM1YSIsInJvbGUiOjB9LHsiYXBwX3V1aWQiOiJjYTIzYzg0Yy1jOTI4LTQ4ZjMtOTU3NS0wOGY1MzBlNWJiOTEiLCJyb2xlIjowfSx7ImFwcF91dWlkIjoiNTU1MjUyMDItMDBmMS00MGI1LWJhMzQtMDNlMWI5MTI3NWM2Iiwicm9sZSI6MH0seyJhcHBfdXVpZCI6IjkyM2QzMjNkLTVmODYtNDAyZS05MjFjLTljNTlhNjM1YmIyZCIsInJvbGUiOjB9XSwiZXhwIjoxNjIxNTMxMzIzLCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI3MGVkMTZmMi04YmYwLTQ3ZjctYmU0Mi02Y2YwMTIwMjE5MmUifQ.81k5-6Vqhxv5h4fleX9DbEXHlu721a2s4aL96Vz40Cg

{
    "app_uuid": "923d323d-5f86-402e-921c-9c59a635bb2d",
    "stages": [
        {
            "id": 1,
            "name": "Stage Zero",
            "transition": "btn_add_to"
        },
        {
            "id": 2,
            "name": "Stage One",
            "transition": "btn_process"
        },
        {
            "id": 3,
            "name": "Stage Two",
            "transition": "btn_buy"
        }
    ]
}

###
POST http://localhost:8080/api/v1/app/config/upsert?flag=campaign HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbeyJhcHBfdXVpZCI6ImQ2NGZmYjdlLWQzODQtNDEyOC04Yjc4LWNlMWQwYTk2OTM1YSIsInJvbGUiOjB9XSwiZXhwIjoxNjIxNDYzNTU1LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI3MGVkMTZmMi04YmYwLTQ3ZjctYmU0Mi02Y2YwMTIwMjE5MmUifQ.Cia4cN92Eo5iIbOkxjCLwaKeh2FnoNcF6B-qtFLAfjw

{
    "app_uuid": "cbd84e62-cb3d-4217-a367-0e343cbb5bc0",
    "records": [
        {
            "id": 1,
            "name": "Summer Sales",
            "prefix": "summer"
        }
    ]
}

###
POST http://localhost:8080/api/v1/app/config/upsert?flag=btn_time HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbeyJhcHBfdXVpZCI6ImQ2NGZmYjdlLWQzODQtNDEyOC04Yjc4LWNlMWQwYTk2OTM1YSIsInJvbGUiOjB9XSwiZXhwIjoxNjIxNDYzNTU1LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiI3MGVkMTZmMi04YmYwLTQ3ZjctYmU0Mi02Y2YwMTIwMjE5MmUifQ.Cia4cN92Eo5iIbOkxjCLwaKeh2FnoNcF6B-qtFLAfjw

{
    "app_uuid": "cbd84e62-cb3d-4217-a367-0e343cbb5bc0",
    "btn_defs": [
        {
            "id": 1,
            "name": "Order Button",
            "btn_name": "btn_order"
        }
    ]
}


### second user

###
GET http://localhost:8080/api/v1/user/profile HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxNDY0OTY0LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiJjNzI4ZGVhNy01M2NhLTQ3MGUtODUzZC00YTUxNzE5NzBiMDQifQ.msO58KBfG7oE55C9u9P80u77BIS8HTRXNq2MjIrz5Zc

###
GET http://localhost:8080/api/v1/user/profile/colleagues HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxNDY0OTY0LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiJjNzI4ZGVhNy01M2NhLTQ3MGUtODUzZC00YTUxNzE5NzBiMDQifQ.msO58KBfG7oE55C9u9P80u77BIS8HTRXNq2MjIrz5Zc

###
POST http://localhost:8080/api/v1/user/profile/update HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxNDY0OTY0LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiJjNzI4ZGVhNy01M2NhLTQ3MGUtODUzZC00YTUxNzE5NzBiMDQifQ.msO58KBfG7oE55C9u9P80u77BIS8HTRXNq2MjIrz5Zc

{
    "first_name": "Konstantin",
    "last_name":  "Gasser",
    "orgn_position": "Software Engineer",
    "profile_img_url": "some/path/to/image"
}

###
POST http://localhost:8080/api/v1/app/create HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxNDY0OTY0LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiJjNzI4ZGVhNy01M2NhLTQ3MGUtODUzZC00YTUxNzE5NzBiMDQifQ.msO58KBfG7oE55C9u9P80u77BIS8HTRXNq2MjIrz5Zc

{
    "app_name": "dummy#1",
    "app_URL":  "http://dummy#1.io",
    "app_description": "App Test #1"
}

###
GET http://localhost:8080/api/v1/app/get?app=d64ffb7e-d384-4128-8b78-ce1d0a96935a HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxNDY0OTY0LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiJjNzI4ZGVhNy01M2NhLTQ3MGUtODUzZC00YTUxNzE5NzBiMDQifQ.msO58KBfG7oE55C9u9P80u77BIS8HTRXNq2MjIrz5Zc

###
GET http://localhost:8080/api/v1/app/getall HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxNDY0OTY0LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiJjNzI4ZGVhNy01M2NhLTQ3MGUtODUzZC00YTUxNzE5NzBiMDQifQ.msO58KBfG7oE55C9u9P80u77BIS8HTRXNq2MjIrz5Zc

###
POST http://localhost:8080/api/v1/app/token/create HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxNDY0OTY0LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiJjNzI4ZGVhNy01M2NhLTQ3MGUtODUzZC00YTUxNzE5NzBiMDQifQ.msO58KBfG7oE55C9u9P80u77BIS8HTRXNq2MjIrz5Zc

{
    "app_name": "dummy#2",
    "app_uuid": "2692042e-df8f-45a4-a50d-fdc0828782d6",
    "owner_domain": "datalab.dev",
    "app_origin": "http://test.io"
}

###
POST http://localhost:8080/api/v1/app/config/upsert?flag=funnel HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxNDY0OTY0LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiJjNzI4ZGVhNy01M2NhLTQ3MGUtODUzZC00YTUxNzE5NzBiMDQifQ.msO58KBfG7oE55C9u9P80u77BIS8HTRXNq2MjIrz5Zc

{
    "app_uuid": "cbd84e62-cb3d-4217-a367-0e343cbb5bc0",
    "stages": [
        {
            "id": 1,
            "name": "Stage Zero",
            "transition": "btn_add_to"
        },
        {
            "id": 2,
            "name": "Stage One",
            "transition": "btn_process"
        },
        {
            "id": 3,
            "name": "Stage Two",
            "transition": "btn_buy"
        }
    ]
}

###
POST http://localhost:8080/api/v1/app/config/upsert?flag=campaign HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxNDY0OTY0LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiJjNzI4ZGVhNy01M2NhLTQ3MGUtODUzZC00YTUxNzE5NzBiMDQifQ.msO58KBfG7oE55C9u9P80u77BIS8HTRXNq2MjIrz5Zc

{
    "app_uuid": "cbd84e62-cb3d-4217-a367-0e343cbb5bc0",
    "records": [
        {
            "id": 1,
            "name": "Summer Sales",
            "prefix": "summer"
        }
    ]
}

###
POST http://localhost:8080/api/v1/app/config/upsert?flag=btn_time HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxNDY0OTY0LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiJjNzI4ZGVhNy01M2NhLTQ3MGUtODUzZC00YTUxNzE5NzBiMDQifQ.msO58KBfG7oE55C9u9P80u77BIS8HTRXNq2MjIrz5Zc

{
    "app_uuid": "cbd84e62-cb3d-4217-a367-0e343cbb5bc0",
    "btn_defs": [
        {
            "id": 1,
            "name": "Order Button",
            "btn_name": "btn_order"
        }
    ]
}
###
POST http://localhost:8080/api/v1/app/member/invite/accept HTTP/1.1
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBzIjpbXSwiZXhwIjoxNjIxNTMwNDQ1LCJpYXQiOiJjb20uZGF0YWxhYi5zZXJ2aWNlLnVzZXItYXV0aGVudGljYXRpb24iLCJvcmduIjoiZGF0YWxhYi5kZXYiLCJzdWIiOiJjNzI4ZGVhNy01M2NhLTQ3MGUtODUzZC00YTUxNzE5NzBiMDQifQ.4gJq4u5k9k-hTCRJWLPsI9FMwMBE6WObyNJMQR8e-bE

{
    "app_uuid": "923d323d-5f86-402e-921c-9c59a635bb2d"
}
